### PR TITLE
fix: 0xA0 need to be treated as space

### LINKED ISSUE #83: [Bug report] 0xA0 character not recognized as a space in table
**Describe the bug**
when pasting from another editor, table content not parse when paste form another md editor (contains 0xA0 as space)

**To Reproduce**
[0xA0.md](https://github.com/Tencent/cherry-markdown/files/7811442/0xA0.md)
1. paste text from attachment 
2. no table show in preview

**Expected behavior**
can show the table in preview

**Screenshots**
Screen Shot 2022-01-05 at 9 35 10 AM

**Environment (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version Version 96.0.4664.110 (Official Build) (x86_64)

### PR DESCRIPTION
**Pull request by hanye9895**
Fixed #83

### CODE REVIEW

File: src/utils/regexp.js [hunk 1]
```diff
@@ -30,7 +30,7 @@ export function isLookbehindSupported() {
   return false;
 }
 
-export const HORIZONTAL_WHITESPACE = '[ \\t]';
+export const HORIZONTAL_WHITESPACE = '[ \\t ]';
```
Comment (lyngai) [inline src/utils/regexp.js:33]: It would be better to use unicode code point `\u00a0` to match non-visible whitespaces.

**Review by lyngai — CHANGES_REQUESTED** [review]

**Review by lyngai — APPROVED** [review]
LGTM
