### PR TITLE
fix(code-block): fix #166 parse hr and indent code

### LINKED ISSUE #166: [Bug report] 在某些场景下不能正确识别 --- 语法
使用如下语法的时候不能正确识别 --- 语法

```
111

---

    code

```
wecom-temp-2849c758339420d041731ad5f51cea70

并且在下边这么写的时候会识别出一些奇怪的东西
```
    111

---

    code
```
wecom-temp-e60ee6cda8177ffb2c5b85cf6436c5cd

### LINKED ISSUE #194: [Bug report] 有序列表后面加了空格，换行内容会消失，可复制以下纯文字部分复现
```
1. 
被隐藏掉的文字
被隐藏掉的文字
2. 测试
```

### PR DESCRIPTION
**Pull request by joriewong**
Fixed #166

### CODE REVIEW

File: src/core/hooks/CodeBlock.js [hunk 1]
```diff
@@ -203,7 +203,7 @@ export default class CodeBlock extends ParagraphBase {
    */
   $getIndentedCodeReg() {
     const ret = {
-      begin: '(?:^|\\n\\s*\\n)(?: {4}|\\t)',
+      begin: '(?<=^|\\n)(?: {4}|\\t)',
```
Comment (lyngai) [inline src/core/hooks/CodeBlock.js:206]: Avoid using lookbehind assertion in regexp. Because not all morden browsers support it, such as Safari.

FYI: https://caniuse.com/?search=lookbehind

**Review by lyngai — CHANGES_REQUESTED** [review]

File: src/core/hooks/CodeBlock.js (hunk 1 above)
Comment (joriewong) [reply src/core/hooks/CodeBlock.js]: use `?:` and `prependLineFeedForParagraph` instead.

**Review by lyngai — APPROVED** [review]
